POST  http://localhost:3003/create-class
Content-Type: application/json

{
   "id": 2,
   "nome":"Epps",
   "data_inicio": "2020-09-15",
   "data_final": "2021-06-01",
   "modulo": 6
}

###

POST  http://localhost:3003/create-teacher
Content-Type: application/json

{
   "id": 11,
   "nome":"Amanda",
   "email": "amanda@labenu.com.br",
   "data_nasc": "1990-05-10",
   "turma_id": 2
}

###

POST  http://localhost:3003/create-student
Content-Type: application/json

{
   
  "id": 10,
   "nome":"Vivian Oliveira",
   "email": "vivian@gmail.com",
   "data_nasc": "1990-01-17",
   "turma_id": 2
}