
PUT  http://localhost:3003/addStudent
Content-Type: application/json

{
   "id": 2,
   "nome":"Newton",
   "data_inicio": "2020-08-15",
   "data_final": "2021-05-16",
   "modulo": 3
}

###

GET http://localhost:3003/age/1